create extension if not exists pgcrypto;
create extension if not exists pgtap with schema extensions;

create table public.schools (id uuid primary key default gen_random_uuid(),name text not null,timezone text not null default 'Asia/Taipei',currency text not null default 'TWD',created_at timestamptz not null default now());
create table public.memberships (school_id uuid not null references public.schools on delete cascade,user_id uuid not null references auth.users on delete cascade,role text not null check(role in('teacher','admin','viewer')),created_at timestamptz not null default now(),primary key(school_id,user_id));
create index memberships_user_id_idx on public.memberships(user_id);
create table public.classes (id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools on delete cascade,name text not null,grade integer not null check(grade between 1 and 12),active boolean not null default true,unique(school_id,name));
create index classes_school_id_idx on public.classes(school_id);
create table public.meal_records (id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools on delete cascade,class_id uuid not null references public.classes,served_on date not null,meal_period text not null default 'lunch' check(meal_period='lunch'),staple text not null,main_dish text not null,side_dishes text[] not null default '{}',menu_signature text not null,planned_people integer not null check(planned_people>0),actual_people integer not null check(actual_people>0),total_supply_g integer not null check(total_supply_g>=0),leftover_g integer not null check(leftover_g>=0 and leftover_g<=total_supply_g),measurement_method text not null check(measurement_method in('scale','manual','ai-estimate')),notes text not null default '',source text not null default 'manual' check(source in('manual','import')),created_by uuid not null default auth.uid() references auth.users,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index meal_records_school_date_idx on public.meal_records(school_id,served_on desc);create index meal_records_class_idx on public.meal_records(class_id);create index meal_records_menu_idx on public.meal_records(school_id,menu_signature,served_on desc);
create table public.plate_scans (id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools on delete cascade,meal_record_id uuid not null references public.meal_records on delete cascade,image_path text,client_request_id uuid not null unique,provider text not null,model text not null,schema_version text not null default '1',status text not null check(status in('confirmed','failed')),reviewed_by uuid not null default auth.uid() references auth.users,reviewed_at timestamptz not null default now(),created_at timestamptz not null default now());
create index plate_scans_school_idx on public.plate_scans(school_id,created_at desc);create index plate_scans_meal_idx on public.plate_scans(meal_record_id);
create table public.scan_detections (id uuid primary key default gen_random_uuid(),scan_id uuid not null references public.plate_scans on delete cascade,school_id uuid not null references public.schools on delete cascade,category text not null check(category in('rice','noodles','meat','vegetable','egg','fruit','other')),label text not null,ai_original_g integer not null check(ai_original_g>0),ai_remaining_ratio numeric(5,4) not null check(ai_remaining_ratio between 0 and 1),ai_remaining_g integer not null check(ai_remaining_g>=0),confidence numeric(5,4) not null check(confidence between 0 and 1),sort_order integer not null);
create index scan_detections_scan_idx on public.scan_detections(scan_id,sort_order);create index scan_detections_school_category_idx on public.scan_detections(school_id,category);
create table public.scan_corrections (id uuid primary key default gen_random_uuid(),detection_id uuid not null unique references public.scan_detections on delete cascade,school_id uuid not null references public.schools on delete cascade,corrected_category text not null check(corrected_category in('rice','noodles','meat','vegetable','egg','fruit','other')),corrected_label text not null,corrected_original_g integer not null check(corrected_original_g>0),corrected_remaining_ratio numeric(5,4) not null check(corrected_remaining_ratio between 0 and 1),corrected_remaining_g integer not null check(corrected_remaining_g>=0),note text not null default '',corrected_by uuid not null default auth.uid() references auth.users,corrected_at timestamptz not null default now());
create index scan_corrections_school_idx on public.scan_corrections(school_id);
create table public.supply_predictions (id text primary key,school_id uuid not null references public.schools on delete cascade,created_by uuid not null default auth.uid() references auth.users,planned_people integer not null,menu_name text not null,planned_supply_g integer not null,recommended_supply_g integer not null,average_leftover_rate numeric(5,4) not null,possible_saving_g integer not null,possible_saving_twd integer not null,confidence text not null check(confidence in('high','medium','low')),match_level text not null check(match_level in('exact','similar','baseline','insufficient')),sample_size integer not null,history_start date,history_end date,reason text not null,algorithm_version text not null,created_at timestamptz not null default now());
create index supply_predictions_school_idx on public.supply_predictions(school_id,created_at desc);
create table public.experiments (id text primary key,school_id uuid not null references public.schools on delete cascade,title text not null,baseline_start date not null,baseline_end date not null,intervention_start date not null,intervention_end date not null,class_id uuid references public.classes,intervention_description text not null,linked_prediction_id text references public.supply_predictions,created_by uuid not null default auth.uid() references auth.users,created_at timestamptz not null default now(),check(baseline_start<=baseline_end and intervention_start<=intervention_end));
create index experiments_school_idx on public.experiments(school_id,created_at desc);
create table public.research_sections (id text primary key,school_id uuid not null references public.schools on delete cascade,slug text not null,title text not null,body_markdown text not null default '',sort_order integer not null,is_published boolean not null default true,updated_by uuid default auth.uid() references auth.users,updated_at timestamptz not null default now(),unique(school_id,slug));
create table public.impact_settings (school_id uuid primary key references public.schools on delete cascade,cost_twd_per_kg numeric(10,2) not null default 80,school_daily_baseline_g integer not null default 0,school_days_per_week integer not null default 5 check(school_days_per_week between 1 and 7),weeks_per_semester integer not null default 20,semesters_per_year integer not null default 2,co2e_factor numeric(12,6),source_title text,source_url text,retrieved_at date,disclaimer text not null,updated_by uuid default auth.uid() references auth.users,updated_at timestamptz not null default now(),check(co2e_factor is null or(source_title is not null and source_url is not null and retrieved_at is not null)));
create table public.project_profiles (school_id uuid primary key references public.schools on delete cascade,project_name text not null,subtitle text not null,school_name text not null,team_name text not null,team_members text not null,research_period text not null,ai_disclosure text not null,updated_by uuid default auth.uid() references auth.users,updated_at timestamptz not null default now());

create or replace function public.set_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end;$$;
create trigger meal_records_updated before update on public.meal_records for each row execute function public.set_updated_at();
create trigger research_sections_updated before update on public.research_sections for each row execute function public.set_updated_at();
create trigger impact_settings_updated before update on public.impact_settings for each row execute function public.set_updated_at();
create trigger project_profiles_updated before update on public.project_profiles for each row execute function public.set_updated_at();

create or replace function public.is_school_member(target_school uuid,allowed_roles text[] default null) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.memberships m where m.school_id=target_school and m.user_id=auth.uid() and(allowed_roles is null or m.role=any(allowed_roles)));$$;
revoke all on function public.is_school_member(uuid,text[]) from public;grant execute on function public.is_school_member(uuid,text[]) to authenticated;

alter table public.schools enable row level security;alter table public.memberships enable row level security;alter table public.classes enable row level security;alter table public.meal_records enable row level security;alter table public.plate_scans enable row level security;alter table public.scan_detections enable row level security;alter table public.scan_corrections enable row level security;alter table public.supply_predictions enable row level security;alter table public.experiments enable row level security;alter table public.research_sections enable row level security;alter table public.impact_settings enable row level security;alter table public.project_profiles enable row level security;
create policy schools_read on public.schools for select to authenticated using(public.is_school_member(id));create policy memberships_read on public.memberships for select to authenticated using(public.is_school_member(school_id));
create policy classes_read on public.classes for select to authenticated using(public.is_school_member(school_id));create policy classes_write on public.classes for all to authenticated using(public.is_school_member(school_id,array['teacher','admin'])) with check(public.is_school_member(school_id,array['teacher','admin']));
create policy meals_read on public.meal_records for select to authenticated using(public.is_school_member(school_id));create policy meals_write on public.meal_records for all to authenticated using(public.is_school_member(school_id,array['teacher','admin'])) with check(public.is_school_member(school_id,array['teacher','admin']));
create policy scans_read on public.plate_scans for select to authenticated using(public.is_school_member(school_id));create policy detections_read on public.scan_detections for select to authenticated using(public.is_school_member(school_id));create policy corrections_read on public.scan_corrections for select to authenticated using(public.is_school_member(school_id));
create policy predictions_read on public.supply_predictions for select to authenticated using(public.is_school_member(school_id));create policy predictions_write on public.supply_predictions for all to authenticated using(public.is_school_member(school_id,array['teacher','admin'])) with check(public.is_school_member(school_id,array['teacher','admin']));
create policy experiments_read on public.experiments for select to authenticated using(public.is_school_member(school_id));create policy experiments_write on public.experiments for all to authenticated using(public.is_school_member(school_id,array['teacher','admin'])) with check(public.is_school_member(school_id,array['teacher','admin']));
create policy research_read on public.research_sections for select to authenticated using(public.is_school_member(school_id));create policy research_write on public.research_sections for all to authenticated using(public.is_school_member(school_id,array['teacher','admin'])) with check(public.is_school_member(school_id,array['teacher','admin']));
create policy impact_read on public.impact_settings for select to authenticated using(public.is_school_member(school_id));create policy impact_write on public.impact_settings for all to authenticated using(public.is_school_member(school_id,array['teacher','admin'])) with check(public.is_school_member(school_id,array['teacher','admin']));
create policy profile_read on public.project_profiles for select to authenticated using(public.is_school_member(school_id));create policy profile_write on public.project_profiles for all to authenticated using(public.is_school_member(school_id,array['teacher','admin'])) with check(public.is_school_member(school_id,array['teacher','admin']));
revoke all on all tables in schema public from anon;grant usage on schema public to authenticated;grant select on public.schools,public.memberships,public.classes,public.meal_records,public.plate_scans,public.scan_detections,public.scan_corrections,public.supply_predictions,public.experiments,public.research_sections,public.impact_settings,public.project_profiles to authenticated;grant insert,update,delete on public.classes,public.meal_records,public.supply_predictions,public.experiments,public.research_sections,public.impact_settings,public.project_profiles to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('plate-images','plate-images',false,5242880,array['image/jpeg','image/png','image/webp']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy plate_images_read on storage.objects for select to authenticated using(bucket_id='plate-images' and public.is_school_member(((storage.foldername(name))[1])::uuid));create policy plate_images_insert on storage.objects for insert to authenticated with check(bucket_id='plate-images' and public.is_school_member(((storage.foldername(name))[1])::uuid,array['teacher','admin']));create policy plate_images_delete on storage.objects for delete to authenticated using(bucket_id='plate-images' and public.is_school_member(((storage.foldername(name))[1])::uuid,array['teacher','admin']));
create or replace function public.block_detection_mutation() returns trigger language plpgsql as $$begin raise exception 'AI original detections are append-only';end;$$;create trigger scan_detections_immutable before update or delete on public.scan_detections for each row execute function public.block_detection_mutation();

create or replace function public.confirm_scan(payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_school uuid=(payload->>'school_id')::uuid;v_meal uuid;v_scan uuid;v_detection uuid;v_request uuid=(payload->>'client_request_id')::uuid;v_item jsonb;v_correction jsonb;v_index integer=0;v_leftover integer=0;v_existing public.plate_scans;
begin
if not public.is_school_member(v_school,array['teacher','admin']) then raise exception 'not authorized';end if;select * into v_existing from public.plate_scans where client_request_id=v_request;if found then return jsonb_build_object('meal_id',v_existing.meal_record_id,'scan_id',v_existing.id);end if;
for v_item in select * from jsonb_array_elements(payload->'corrections') loop v_leftover=v_leftover+coalesce((v_item->>'remainingG')::integer,0);end loop;
insert into public.meal_records(school_id,class_id,served_on,meal_period,staple,main_dish,side_dishes,menu_signature,planned_people,actual_people,total_supply_g,leftover_g,measurement_method,notes,source,created_by) values(v_school,(payload#>>'{meal,class_id}')::uuid,(payload#>>'{meal,served_on}')::date,'lunch',payload#>>'{meal,staple}',payload#>>'{meal,main_dish}',array(select jsonb_array_elements_text(payload#>'{meal,side_dishes}')),lower((payload#>>'{meal,staple}')||'|'||(payload#>>'{meal,main_dish}')),(payload#>>'{meal,planned_people}')::integer,(payload#>>'{meal,actual_people}')::integer,(payload#>>'{meal,total_supply_g}')::integer,v_leftover,payload#>>'{meal,measurement_method}',coalesce(payload#>>'{meal,notes}',''),'manual',auth.uid()) returning id into v_meal;
insert into public.plate_scans(school_id,meal_record_id,image_path,client_request_id,provider,model,schema_version,status,reviewed_by) values(v_school,v_meal,payload->>'image_path',v_request,payload#>>'{analysis,provider}',payload#>>'{analysis,model}','1','confirmed',auth.uid()) returning id into v_scan;
for v_item in select * from jsonb_array_elements(payload#>'{analysis,detections}') loop v_correction=payload->'corrections'->v_index;insert into public.scan_detections(scan_id,school_id,category,label,ai_original_g,ai_remaining_ratio,ai_remaining_g,confidence,sort_order) values(v_scan,v_school,v_item->>'category',v_item->>'label',(v_item->>'originalG')::integer,(v_item->>'remainingRatio')::numeric,(v_item->>'remainingG')::integer,(v_item->>'confidence')::numeric,v_index) returning id into v_detection;if v_correction is not null and(v_correction->>'category'<>v_item->>'category' or v_correction->>'label'<>v_item->>'label' or v_correction->>'originalG'<>v_item->>'originalG' or v_correction->>'remainingRatio'<>v_item->>'remainingRatio') then insert into public.scan_corrections(detection_id,school_id,corrected_category,corrected_label,corrected_original_g,corrected_remaining_ratio,corrected_remaining_g,note,corrected_by) values(v_detection,v_school,v_correction->>'category',v_correction->>'label',(v_correction->>'originalG')::integer,(v_correction->>'remainingRatio')::numeric,(v_correction->>'remainingG')::integer,'學生人工確認與修正',auth.uid());end if;v_index=v_index+1;end loop;return jsonb_build_object('meal_id',v_meal,'scan_id',v_scan);end;$$;
revoke all on function public.confirm_scan(jsonb) from public;grant execute on function public.confirm_scan(jsonb) to authenticated;
